name: Upload Artifact
description: Uploads build artifact
inputs:
  name:
    required: true
  path:
    required: true
  env:
    required: true
  version:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-${{ inputs.env }}-${{ inputs.version }}
        path: ${{ inputs.path }}
        #path: artifact-repo
